import TableResponsive from './components/TableResponsive.js';
import Card from './components/Card.js';
import BackButton from './components/BackButton.js';
import NavBar from './components/NavBar.js';
import Main from './components/Main.js';
import AlertCard from "./components/AlertCard.js";

const urlParams = new URLSearchParams(window.location.search);
const id = urlParams.get('id');
const query = urlParams.get('query');

async function fetchListingDateData(id, query) {
    if (id === 'dates') {
        // Remove the "/" from query
        const date = query.replace(/\//g, '');

        try {
            // Get the .json file named "listing_date_<date>.json"
            const response = await fetch(`scripts/listing_date_${date}.json`);
            return await response.json();
        } catch (err) {
            console.error(err);
            return err;
        }
    } else if (id === 'clients' || id === 'campaigns_id' || id === 'similar_errors') {
        try {
            const listingDatesResponse = await fetch('scripts/listing_dates.json');
            const listingDates = await listingDatesResponse.json();

            let listingDatesData = listingDates.map(async date => {
                const formatedDate = date.replace(/\//g, '');
                return await fetchListingDateData('dates', formatedDate);
            });

            listingDatesData = await Promise.all(listingDatesData);

            listingDatesData = listingDatesData.reduce((acc, val) => {
                acc.total_erros += val.total_erros;
                acc.contagem_metodos = {...acc.contagem_metodos, ...val.contagem_metodos};
                acc.contagem_crms = {...acc.contagem_crms, ...val.contagem_crms};
                acc.contagem_erros_similares = {...acc.contagem_erros_similares, ...val.contagem_erros_similares};
                acc.dados = [...acc.dados, ...val.dados];
                return acc;
            });

            // TODO: if id is 'clients' or 'campaigns_id' or 'similar_errors' return the data grouped by the id by the dados key and recalculate the total_erros, contagem_metodos, contagem_crms and contagem_erros_similares


            return listingDatesData;
        } catch (err) {
            console.error(err);
            return err;
        }
    }
}

function createElementWithContent(tag, content, className) {
    const element = document.createElement(tag);
    if (className) element.className = className;
    element.innerHTML = content;
    return element;
}

function renderCardTableDetailedData(header, renderTo, data) {
    const headers = ['View', 'Message', 'Date', 'Client', 'Campaign', 'Call ID'];

    const rows = data.map(item => {
        let view = `<a href="report-listing.html?id=dates&query=${query}" aria-label="Gera um relatório com todos os erros de uma data específica">
            <svg fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
            </svg>
        </a>`;

        let message = item.mensagem;
        let date = item.data;
        let client = item.carteira;
        let campaign = item.fila;
        let callid = item.callid;

        return [view, message, date, client, campaign, callid];
    });

    const table = TableResponsive({headers, rows});
    const card = Card({title: header, cardBody: table});

    renderTo.appendChild(createElementWithContent('div', card, 'centered-div'));
}

function renderCardTable(header, renderTo, data, headers, subheader=null) {
    const rows = Object.entries(data).map(([key, value]) => [key, value]);

    const table = TableResponsive({headers, rows});

    return Card({title: header, cardBody: table, subheader: subheader});
}

function removeLoader() {
    const loader = document.querySelector('#loading');
    setTimeout(() => {
        loader.remove();
    }, 1500);
}

function renderBackButton() {
    const containerSmall = document.querySelector('.container-small');
    const backButton = BackButton();
    containerSmall.appendChild(backButton);
}

await fetchListingDateData(id, query).then(data => {
    console.log(data);

    const body = document.querySelector('body');
    body.appendChild(NavBar());
    body.appendChild(Main());
    renderBackButton();

    const containerSmall = body.querySelector('main .container-small');

    const article = `
        <article>
            <p>This report was automatically generated by the system. The data presented here refer to the Log_Dev.log file read on 09/03/2024 at 11:00 AM.</p>
            <p>A total of 167 errors were found.</p>
            <p>Note: The data presented may be incorrect as they depend on the correct formatting of the Log_Dev.log file.</p>
        </article>
    `;

    const methods = data.contagem_metodos;
    const clients = data.contagem_crms;
    const averageClientErrors = Object.values(clients).reduce((acc, val) => acc + val, 0) / Object.keys(clients).length;
    const similarErrors = data.contagem_erros_similares;
    const detailedData = data.dados

    console.log(data);

    const card = Card({title: 'Error Report Grouped By Date', cardBody: article, subheader: 'Generated on 09/03/2024 at 11:53'});
    const alertCard = AlertCard({titles: [
            {key: data.total_erros, value: 'Total Errors'},
            {key: Object.keys(clients).length, value: 'Clients with Errors'},
            {key: averageClientErrors, value: 'Average Client Errors'},
            {key: Object.keys(similarErrors).length, value: 'Type of Errors'}
        ]}
    );

    const methodsCard = renderCardTable('Methods', containerSmall, methods, ['Method', 'Count'], 'Count by method grouping');
    const clientsCard = renderCardTable('Clients', containerSmall, clients, ['Client', 'Count'], 'Count by client grouping');
    const similarErrorsCard = renderCardTable('Similar Errors', containerSmall, similarErrors, ['Error', 'Count'], 'Count by error grouping');

    containerSmall.appendChild(createElementWithContent('article', card, 'centered-div'));

    containerSmall.appendChild(createElementWithContent('div', alertCard, 'centered-div'));

    const row = createElementWithContent('div', '', 'row');
    row.appendChild(createElementWithContent('div', methodsCard, 'col'));
    row.appendChild(createElementWithContent('div', clientsCard, 'col'));
    containerSmall.appendChild(row);

    containerSmall.appendChild(createElementWithContent('div', similarErrorsCard, 'centered-div'));
    renderCardTableDetailedData('Detailed Data', containerSmall, detailedData);

    removeLoader();
}).catch(err => {
    console.error(err);
    removeLoader();
});